### PR TITLE
AvaTax BR API Update

### PR DESCRIPTION
**Pull request by everton-amorim-avalara**
AvaTax BR API Update

### CODE REVIEW

**Comment by benfjohnson** [comment]
Hey @everton-amorim-avalara, looks like you have some conflicts with upstream -- if you can resolve those I'll pull down the changes and check it out, thanks!

**Comment by everton-amorim-avalara** [comment]
Hi @benfjohnson ! I don't have access to resolve the conflits (see image below), if you can give this access to me i can solve it, if not you can solve with this plan:
"Gemfile.lock" - Ignore my changes and keep the lastest master version.
Other files - ignore the repository changes and keep my changes.

Thanks!

screen shot 2017-06-07 at 10 42 32 am

**Comment by benfjohnson** [comment]
@everton-amorim-avalara while you don't have permissions to directly resolve that conflict, you should have permissions to merge in the latest Avalara/developer-dot changes into your repo. If you have Avalara/developer-dot added as your `upstream` remote (`git remote add upstream https://github.com/Avalara/developer-dot.git`), you should be able to `git fetch upstream` and then `git merge upstream/master` into your fork. From there, you'll be able to resolve the conflicts in your own fork, which will fix your PR the next time you `push`. If that's not the case, I can make sure you get the right permissions. Thanks.

**Comment by everton-amorim-avalara** [comment]
Thanks @benfjohnson! I followed your instructions and solve the conflicts.

**Comment by everton-amorim-avalara** [comment]
@benfjohnson i got a "The command "docker-compose up --abort-on-container-exit --exit-code-from server" exited with 1." error from CI, could you help me? if not, who can help me?

**Comment by benfjohnson** [comment]
@everton-amorim-avalara I'll take a look and see if I can't diagnose the issue.

**Comment by benfjohnson** [comment]
@everton-amorim-avalara your changes are now live! I took this PR and made a few changes (we recently made some large structural changes to the site that broke a couple of your links), and created a new PR that just merged. Going to close this now as it's outdated.

**Pull request closed without merging**
