### PR TITLE
Brazil API Updates

### PR DESCRIPTION
**Pull request by everton-amorim-avalara**
Brazil API Updates - Added Compliance API, fix "Maximum call exceed" error while generating compliance's pages.

### CODE REVIEW

**Comment by benfjohnson** [comment]
We'll need to do some sanity testing before merging this, as these changes would affect API documentation for all of our products. Generally when I see those "maximum call stack size exceeded" errors, they can be fixed by tracking down a swagger definition that's formatted unexpectedly.

**Comment by everton-amorim-avalara** [comment]
Hi @benfjohnson! Ok, no worry about the sanity tests! We just fix that error that considered a string as an array! When could you do this test? I just need a schedule to forward to Matt and Zerlotti.

**Comment by benfjohnson** [comment]
@everton-amorim-avalara I should be able to take a look at it this afternoon, will let you how everything looks here

**Comment by everton-amorim-avalara** [comment]
@benfjohnson Ok, we restored the helper.js and remove the circular references on compliance.json.

**Comment by benfjohnson** [comment]
Great!

**Pull request merged**
