### PR TITLE
DX-418: Loading animation for API Console

### PR DESCRIPTION
**Pull request by JoshBlanks**
Ticket: https://avalara.atlassian.net/browse/DX-418

Created loading animation for when Submit button is clicked on the API Console to acknowledge and show the user that we're processing their request (on the instance that response is a bit slow).

### CODE REVIEW

**Comment by JeremyCraigMartinez** [comment]
Just realized that this isn't enabled for [get-started](http://localhost:4000/avatax/get-started/) @JoshBlanks

**Comment by JoshBlanks** [comment]
Okay, will look to fix/add that

**Comment by JoshBlanks** [comment]
@JeremyCraigMartinez Should be good to go - check it out!

**Comment by JeremyCraigMartinez** [comment]
Seeing quite a few warnings in console on load for getting started but it seems to be working just fine :+1:

**Pull request merged**
